name: "Release - Publish Feature"

on:
  push:
    branches: [main, master]
    paths:
      - "src/**"
      - ".github/workflows/release.yaml"
  workflow_dispatch:

jobs:
  deploy:
    name: "Publish to GHCR"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
